### root access

GET http://localhost:8000

### login api end point
POST   http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "aaa@gmail.com",
    "password": "12345",
    
}

###login api end point
PUT  http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "aaa@mail.com",
    "password": "12345",
    "fname":"Anup",
    "lname": "Poudel",
    "role": "admin"
    
}

### Category ###
### Fetch all category 
GET http://localhost:8000/api/v1/category

### DELETE a category 
DELETE  http://localhost:8000/api/v1/category


### Add a category 
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{"name" : "Root Category" , "parentCat" :0 }

### Product APIS ###
### fetch all products
GET http://localhost:8000/api/v1/product

#### fetch single product
GET http://localhost:8000/api/v1/product/607a78dc63f3140648f5eecd


###
POST http://localhost:8000/api/v1/product
Content-Type: application/json

{"name" : "Root Category" , 
"price" :0
 }

### fetch single product 
PUT http://localhost:8000/api/v1/product
Content-Type: application/json

{"_id": "607a78dc63f3140648f5eecd"}
 

